#pragma once

#include "Precompiled.hpp"

/*
    Build

    Stores information generated by the build system.

    void ExampleBuild()
    {
        // Initialize the build info.
        Build::Initialize();

        // Retrive some build info.
        Log() << "Working directory: " << Build::GetWorkingDir();
        Log() << "Source directory: " << Build::GetSourceDir();
    }
*/

namespace Build
{
    // Loads info generated by the build system.
    void Initialize(std::string executablePath);

    // Gets the working directory specified by the build system.
    std::string GetWorkingDir();

    // Gets the source directory specified by the build system.
    std::string GetSourceDir();

    // Gets the build's change list number.
    std::string GetChangeList();

    // Gets the build's commit hash.
    std::string GetCommitHash();

    // Gets the build's commit date.
    std::string GetCommitDate();

    // Gets the build's branch name.
    std::string GetBranchName();
}
