#pragma once

#include "Precompiled.hpp"

/*
    Build

    Stores information generated by the build system.

    void ExampleBuild(int argc, char* argv[])
    {
        // Initialize the build info.
        Build::Initialize(argc, argv);

        // Retrive some build info.
        Log() << "Working directory: " << Build::GetWorkingDir();
        Log() << "Source directory: " << Build::GetSourceDir();
    }
*/

namespace Build
{
    // Loads info generated by the build system.
    // Requires program's arguments from main() to be forwarded.
    void Initialize(int argc, char* argv[]);

    // Gets the working directory specified by the build system.
    std::string GetWorkingDir();

    // Gets the source directory specified by the build system.
    std::string GetSourceDir();

    // Gets the build's change list number.
    std::string GetChangeList();

    // Gets the build's commit hash.
    std::string GetCommitHash();

    // Gets the build's commit date.
    std::string GetCommitDate();

    // Gets the build's branch name.
    std::string GetBranchName();
}
